### ISSUE TITLE
job_manager create_job api call expects 4 arguments but it is called with 3 from main.py

### ISSUE THREAD

**Issue by yunus** [GoogleCloudPlatform/datacatalog-tag-engine#117]
create_job function needs 4 parameters while only 3 have been provided. I observe this error in the `cloud_run` branch.

In [main.py](https://github.com/GoogleCloudPlatform/datacatalog-tag-engine/blob/cloud-run/main.py#L741) under `process_created_config_action` we call create_job:

```python
if action == "Trigger Job":
        job_uuid = jm.create_job(service_account, config_uuid, config_type)
        job = jm.get_job_status(job_uuid)
```

However, create_job function under [job_manager.py](https://github.com/GoogleCloudPlatform/datacatalog-tag-engine/blob/a60e460b161a8965b9e34c1b72daec0960eaa743/JobManager.py#L49) accepts 4 arguments:

```python
    def create_job(self, tag_creator_account, tag_invoker_account, config_uuid, config_type, metadata=None):
        
        print('*** enter create_job ***')
        print('config_uuid: ', config_uuid, ', config_type: ', config_type)
```

Then we get 500 errors while creating a new job.

**Comment by shirleycohen** [comment]
Fixed in [v2.1.9](https://github.com/GoogleCloudPlatform/datacatalog-tag-engine/releases/tag/v2.1.9).
