### ISSUE TITLE
 Use db firestore with a name other than (default)

### ISSUE THREAD

**Issue by francescpuig7** [GoogleCloudPlatform/datacatalog-tag-engine#118]
By default, tag engine works with the native firestore database called (default).
Be able to use a db with a different name

**Comment by shirleycohen** [comment]
Thanks for your PR @francescpuig7. Are you able to sign the [CLA]( https://cla.developers.google.com/) ? This will allow us to add you as a contributor and merge your PR into the main branch.

**Comment by francescpuig7** [comment]
Yes @shirleycohen, done!

**Comment by shirleycohen** [comment]
francescpuig7@ apologies for not merging your PR. By the time I reviewed it, there were several merge conflicts. This functionality has been added to [v2.2.9.](https://github.com/GoogleCloudPlatform/datacatalog-tag-engine/releases/tag/v2.2.9). Please take a look when you get a chance.
