### ISSUE TITLE
Missing documentation when creating a Config with Refresh Mode set to Auto

### ISSUE THREAD

**Issue by HarukaIzumisawa** [GoogleCloudPlatform/datacatalog-tag-engine#123]
I would like to create a Config with `Refresh Mode` set to `Auto` to achieve scheduled tag updates.
However, there is no detailed explanation in the [`ui_guide.md`](https://github.com/GoogleCloudPlatform/datacatalog-tag-engine/blob/b64520a4780e66e72215efd5cf530e3f87b61059/docs/ui_guide.md#-dynamic-tag-table).
I think I need to request the `scheduled_auto_updates` function after creating the Config in order to perform scheduled updates.
The source code states that this method is requested by Cloud Scheduler, but the documentation does not describe the procedure for creating this Cloud Scheduler job.
https://github.com/GoogleCloudPlatform/datacatalog-tag-engine/blob/b64520a4780e66e72215efd5cf530e3f87b61059/main.py#L3040-L3044
Therefore, we propose the following

Proposal:
- Add documentation on the behavior of `Refresh Mode` when set to `Auto`.
- Add documentation on how to create and configure a Cloud Scheduler job.

**Comment by shirleycohen** [comment]
I've updated [api_reference.md](https://github.com/GoogleCloudPlatform/datacatalog-tag-engine/blob/cloud-run/docs/api_reference.md) with the details. Please note that this function is only available from the API (not UI).
