### ISSUE TITLE
Coverage Report: rules

### ISSUE THREAD

**Issue by shirleycohen** [GoogleCloudPlatform/datacatalog-tag-engine#2]
Need a better way to quickly see what’s been tagged and what hasn’t been tagged. 

Set up rules such as every table or view in this project/dataset should have these three tags.

**Comment by Chalom1423** [comment]
Hi I see you're dealing with Python
I would love it if you could help me with my homework

I'm currently taking a pretty basic course in Python and the question demands it that way.

The tester, brings me a list of hydrogen carbon compounds:
list = [CH3, CH4, C2H6, C3H20, C2H12 [

Enter any index from 0 to 4, and the program selects a compound from the list. According to its index.
The compounds should adhere to the following formula:
CnHr

r = 2n + 2.

If it holds, some string is printed.
If not, another string is printed.

My problem is with strings where the numbers become double digits.
How do you resolve the issue?

**Comment by shirleycohen** [comment]
Duplicate of ISSUE #13.
