### ISSUE TITLE
AttributeError: 'list' object has no attribute 'isoformat'

### ISSUE THREAD

**Issue by helensilva14** [GoogleCloudPlatform/datacatalog-tag-engine#47]
Getting the error below with the code that gets the timestamp value. Working on it to find a workaround/fix!

```
File "/srv/main.py", line 2575, in _run_task
    creation_status = dcu.apply_dynamic_config(config['fields'], uri, config['config_uuid'], \
  File "/srv/DataCatalogUtils.py", line 311, in apply_dynamic_config
    tag, error_exists = self.populate_tag_field(tag, field_id, field_type, field_value, store)
  File "/srv/DataCatalogUtils.py", line 1528, in populate_tag_field
    timestamp_value = field_value.isoformat()
AttributeError: 'list' object has no attribute 'isoformat'
```

**Comment by shirleycohen** [comment]
Hi @helensilva14, can you please retest? I think this bug was fixed several months ago.

**Comment by helensilva14** [comment]
> Hi @helensilva14, can you please retest? I think this bug was fixed several months ago.

Hi Shirley! Unfortunately I don't have the solution up and running available anymore to be able to test it quickly so for that reason I'll close the issue then!
