### ISSUE TITLE
Missing $VPC_CONNECTOR variable

### ISSUE THREAD

**Issue by adityaPawarDT2** [GoogleCloudPlatform/datacatalog-tag-engine#88]
On executing below command
**gcloud beta run deploy tag-engine-ui \
        --source . \anaged \
        --platform managed \_REGION \
        --region $TAG_ENGINE_REGION \
        --allow-unauthenticated \oud-load-balancing \
        --ingress=internal-and-cloud-load-balancing \
        --port=8080 \es=0 \
        --min-instances=0 \
        --max-instances=5 \CLOUD_RUN_SA \
        --service-account=$CLOUD_RUN_SA \INE_PROJECT/locations/$TAG_ENGINE_REGION/connectors/$VPC_CONNECTOR \
        --vpc-connector=projects/$TAG_ENGINE_PROJECT/locations/$TAG_ENGINE_REGION/connectors/$VPC_CONNECTOR \
        --vpc-egress=private-ranges-only**
This command is equivalent to running `gcloud builds submit --tag [IMAGE] .` and `gcloud run deploy tag-engine-ui --image [IMAGE]`

Building using Dockerfile and deploying container to Cloud Run service [tag-engine-ui] in project [cdmc-gov-003] region [europe-west2]
X  Building and deploying new service... Building Container.                                                                                    
  OK Uploading sources...                                                                                                                       
  OK Building Container... Logs are available at [XXX].                                                                                                                             
  .  Creating Revision...                                                                                                                       
  .  Routing traffic...                                                                                                                         
  .  Setting IAM Policy...                                                                                                                      
Deployment failed                                                                                                                               
ERROR: (gcloud.beta.run.deploy) spec.template.metadata.annotations: Expected a VPC access connector name like projects/*/locations/*/connectors/*, but obtained projects/TAG_ENGINE_PROJECT/locations/europe-west2/connectors/

**Comment by shirleycohen** [comment]
Thanks for flagging @adityaPawarDT2

I've added some verbiage on the `$VPC_CONNECTOR` variable. 

"The next command requires a VPC access connector. This is used to send requests to your VPC network from Cloud Run using internal DNS and internal IP addresses as opposed to going through the public internet. To create a connector, consult [this page](https://cloud.google.com/vpc/docs/configure-serverless-vpc-access#gcloud)."

Does this help?
